# API process entrypoint. Lifecycle only; di wires impl.
load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "cmd_lib",
    srcs = ["main.go"],
    importpath = "github.com/tcw165/fintech-fun/api_server/cmd",
    visibility = ["//visibility:private"],
    deps = [
        "//api_server/di",
        "@com_github_spf13_cobra//:cobra",
        "@org_uber_go_fx//:fx",
    ],
)

go_binary(
    name = "api_server",
    embed = [":cmd_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "cmd_test",
    srcs = ["cmd_test.go"],
    embed = [":cmd_lib"],
)
