# HTTP server. Child of //api_server/contract.
load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "impl",
    srcs = [
        "fold.go",
        "graph.go",
        "search.go",
        "server.go",
    ],
    importpath = "github.com/tcw165/fintech-fun/api_server/impl",
    visibility = ["//visibility:public"],
    deps = [
        "//api_server/contract",
        "//graph",
        "//graph/clients/neo4j",
        "//graph/clients/qdrant",
        "//graph/embed",
    ],
)

go_test(
    name = "impl_test",
    srcs = ["server_test.go"],
    deps = [
        ":impl",
        "//api_server/contract",
        "//graph/clients/neo4j/impl",
        "//graph/clients/qdrant/impl",
        "//graph/embed/lexical",
    ],
)
