load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "hello_agent",
    srcs = ["hello_agent.py"],
    imports = ["."],
    deps = [
        requirement("google-adk"),
    ],
)

py_test(
    name = "hello_agent_test",
    srcs = [
        "__test__.py",
        "hello_agent_test.py",
    ],
    main = "__test__.py",
    deps = [
        ":hello_agent",
        requirement("pytest"),
    ],
)
